### ISSUE TITLE
Tracking: ELF binaries

### ISSUE THREAD

**Issue by riptl** [solana-foundation/specs#10]
The Solana on-chain runtime accepts programs as a subset of the ELF64 format.

**Proposed Content**

- [ ] Accepted subset of the ELF64 ABI
- [ ] Latest validation rules (strict)
- [ ] Backwards-compatibile validation rules
- [ ] Loading algorithm

**Organization**

- *Section:* Runtime
- *Status*: Standard, live on mainnet

**Comment by terorie** [comment]
Useful resources:
- Rust implementation: https://docs.rs/solana_rbpf/latest/solana_rbpf/elf_parser/index.html
- Go implementation: https://pkg.go.dev/go.firedancer.io/radiance/pkg/sbf/loader
