### ISSUE TITLE
Tracking: SBF Syscalls

### ISSUE THREAD

**Issue by riptl** [solana-foundation/specs#11]
Related to #6 -- Document the syscalls available to Solana Bytecode

**Proposed Content**

- [ ] Generic syscall ABI
- [ ] Syscall-specific ABI
- [ ] Syscall implementation pseudocode
- [ ] ABIv2

**Organization**

- *Section:* Runtime
- *Status*: Standard, live on mainnet
